### ISSUE TITLE
Question: Is it possible to merge intermediate files and continue calling methylation?

### ISSUE THREAD

**Issue by sdemirci** [nanoporetech/megalodon#10]
Hello,

I was wondering if I can speed up megalodon by running it on different cluster nodes with batches of fast5 and then merge the intermediate files (for example  _per_read_modified_base_calls.db_ or _per-read modified bases text file_) which then fed to megalodon to call final modifications. I checked the `megalodon/scripts/run_aggregation.py` code but couldn't figure it out what it takes as input. Can you give some advise on these?

**Comment by marcus1487** [comment]
The `per_read_modified_base_calls.db` (and `per_read_snp_calls.db`) is indeed the file that is accessed by the `megalodon/scripts/run_aggregation.py` script specified via the `--output-directory` argument. A script to merge these files (or full runs) has not yet been created and thus merging different runs is not currently available. The database schema for both modified bases and sequence variants are also currently under development, in order to optimize several megalodon operations. Once the database schemas have been finalized a merge script can be developed.

**Comment by marcus1487** [comment]
A pair of scripts have been added in f465ee5 to merge either a set of modified base databases or sequence variant databases.

**Comment by marcus1487** [comment]
As part of the coming release `1.0.0` the `snps` module has been moved to the `variants` module (backwards incompatibly). This is the reason for the error.

The `snps` module name was an artifact from the original development of the code, but this name is misleading since megalodon can detect both single nucleotide polymorphisms as well as small indels, thus the global change from `snps` to `variants`.
