### ISSUE TITLE
Read processing rates decreasing with large input

### ISSUE THREAD

**Issue by MrKevinDC** [nanoporetech/megalodon#100]
I have executed the following command:

`megalodon fast5Folder --guppy-server-path ./ont-guppy/bin/guppy_basecall_server --output-directory megalodon_results --reference GRCh38.primary_assembly.genome.fa.gz --guppy-config res_dna_r941_min_modbases_5mC_v001.cfg --outputs basecalls mappings mod_mappings mods per_read_mods --write-mods-text --guppy-timeout 30 --reads-per-guppy-batch 50 --processes 8 --devices cuda:all:100%`

`fast5Folder` contains 850 FAST5 files, consisting of approximately 180GB of data, or 3.3M reads. 

Read processing speed starts at 57 reads/s and decays steadily until it is currently at 13 reads/s after 70 hours of runtime and 98% completion. I have read other closed issues which associated this decay with including modified base calling in the run, however it was apparently closed and fixed in a recent update. Is this behavior expected? Do you recommend processing so many reads at once?

**Comment by MrKevinDC** [comment]
In fact, 20k reads left to do, it has been 2 hours since the last time it has printed any updates, stuck at 99% processing.

**Comment by idelvall** [comment]
These are the last lines printed out that Kevin mentioned:
```
[2021/02/22 01:37:01] Read Processing: 99%|█████████▉| 3351851/3371560 [72:16:45<25:30, 12.88reads/s, samples/s=4.82e+5]
[2021/02/22 01:37:02] Read Processing: 99%|█████████▉| 3351857/3371560 [72:16:45<25:29, 12.88reads/s, samples/s=4.82e+5]
[2021/02/22 01:37:02] Read Processing: 99%|█████████▉| 3351863/3371560 [72:16:46<25:29, 12.88reads/s, samples/s=4.82e+5]
[2021/02/22 01:37:03] Read Processing: 99%|█████████▉| 3351869/3371560 [72:16:47<25:28, 12.88reads/s, samples/s=4.82e+5]
[2021/02/22 01:37:04] Read Processing: 99%|█████████▉| 3351875/3371560 [72:16:47<25:28, 12.88reads/s, samples/s=4.82e+5]
[2021/02/22 01:37:06] Read Processing: 99%|█████████▉| 3351881/3371560 [72:16:48<25:27, 12.88reads/s, samples/s=4.82e+5]
[2021/02/22 01:37:07] Read Processing: 99%|█████████▉| 3351887/3371560 [72:16:51<25:27, 12.88reads/s, samples/s=4.82e+5]
[2021/02/22 01:37:08] Read Processing: 99%|█████████▉| 3351893/3371560 [72:16:52<25:26, 12.88reads/s, samples/s=4.82e+5]
[2021/02/22 01:37:08] Read Processing: 99%|█████████▉| 3351899/3371560 [72:16:53<25:26, 12.88reads/s, samples/s=4.82e+5]
[2021/02/22 01:37:09] Read Processing: 99%|█████████▉| 3351905/3371560 [72:16:53<25:25, 12.88reads/s, samples/s=4.82e+5]
[2021/02/22 01:37:10] Read Processing: 99%|█████████▉| 3351911/3371560 [72:16:54<25:25, 12.88reads/s, samples/s=4.82e+5]
[2021/02/22 01:37:12] Read Processing: 99%|█████████▉| 3351917/3371560 [72:16:55<25:24, 12.88reads/s, samples/s=4.82e+5]
[2021/02/22 01:37:30] Read Processing: 99%|█████████▉| 3351923/3371560 [72:16:56<25:24, 12.88reads/s, samples/s=4.82e+5]
```
As you can see the rate is actually lower than he said, given that the one reported is the mean rate since startup.
No other output file has been updated since then, but still there are some processes running (almost idle)

So we have two questions:
- Can we avoid this degradation in performance somehow, for large inputs?
- Is our current job state recoverable?

**Comment by marcus1487** [comment]
There are a couple issues around this that I have experienced on large runs. There is no reason that megalodon *should* lose performance on very large data sets, but that does not mean there aren't lingering bugs here.

The first guess would be a stuck output process. I've found that the text output can slow processing, but generally not to this degree. Could you run tail on your stderr output file for this run to see the status of the output queues? You may have to tail quite a large number of lines to get the last updates (I've had to do `tail -100000 stderr.txt` on some runs internally to see that last output).

The other potential issue is dying worker processes. The worker processes are supposed to catch any error within a single read and stay alive, but it is possible that the worker processes have died (e.g. an unexpected segfault). If you could send the log file I could search for signs of worker processes quitting unexpectedly.

Unfortunately, the current state is likely not completely recoverable in order to proceed with processing all reads. The output thus far should be usable though. The modified base database can be indexed with the `megalodon_extras modified_bases index_database` command and the aggregated mods output can be computed using the `megalodon_extras aggregate run` command.

For runs this large I might recommend splitting into subsets of FAST5 files and merging the results (`megalodon_extras merge modified_bases` or `megalodon_extras merge aggregated_modified_bases`). The final results from split runs and running altogether should be identical (aside from reads that fail due to compute/guppy server issues). All relevant computations are made on the per-read level.

**Comment by idelvall** [comment]
Thanks for the response Marcus, your splitting recommendation looks promising.

My impression is that in the processing of a single read there is a `O(N)` operation involved, being `N` the number of reads processed so far. Here is some data we collected, I didn't noticed anything relevant, but hopefully you'll do:

## Processes after the innactivity occurred
![Screenshot from 2021-02-22 15-08-21](https://user-images.githubusercontent.com/5653455/108917219-b2c92800-762f-11eb-88f4-d9a36d27b446.png)

## Output size
```
megalodon_results
├── [24.1 GiB] basecalls.fastq
├── guppy_log
│   └── [11.6 KiB] guppy_basecall_server_log-2021-02-19_12-18-41.log
├── [0 B] guppy_log.err
├── [714 B] guppy_log.out
├── [1.0 GiB] log.txt
├── [4.2 GiB] mappings.bam
├── [362.2 MiB] mappings.summary.txt
├── [4.5 GiB] mod_mappings.bam
├── [62.2 GiB] per_read_modified_base_calls.db
├── [206.6 GiB] per_read_modified_base_calls.txt
└── [712.0 MiB] sequencing_summary.txt
```
## Logs
https://drive.google.com/file/d/1RDLMgTnXjKPl3pN5BsWxztRJgqSIieff/view?usp=sharing

## Storage
SSD, 400 GB free at the time of the event

**Comment by marcus1487** [comment]
There really shouldn't be an `O(N)` operation. The per-read storage format in previous versions had some such operations, but these were removed. I do notice in the htop output that there are a number of megalodon processes in a zombie state. This indicates that they have exited, but not joined with the main thread. This does indicate that something is causing these processes to exit prematurely and thus processing is slowed since worker processes are slowly dying throughout a run (not because of an `O(N)` operation within megalodon. I'll have a look in the log and let you know if I see something useful.

**Comment by marcus1487** [comment]
My suspicion appears to be correct. At 12:50:50-12:52:52 there are a number of workers that have to re-connect to the guppy server. This is somehow triggering the minimap mapper processes connected to these processes to be shutdown prematurely. This is likely stalling these worker processes indefinitely as the reads are sent to be mapped and no response will be returned. I don't have a fix for this right off, but I'm hopeful that some planned updates coming in (hopefully) the next release will address this issue. There have been a number of issues pop up since the guppy 4.4 update causing guppy server connection issues within megalodon.

You can see this by grep'ing out the most common lines in the log with this command: `grep -v "Starting\|Processing\|ReadIDsExtractedFrom\|Success\|BasecallingCompleted\|alignment" log.txt`.

For some background this slightly complicated setup (guppy+read processing in one process and minimap in another) was done so that the minimap index can be loaded into shared memory while the basecalling and modified base calling can be performed in different processes (thus avoiding the GIL). Might be too much detail, but just to help in understanding the inner workings here.

**Comment by idelvall** [comment]
Thanks for the explanation Marcus, we are glad we helped you identifying the problem.

> thus avoiding the GIL
Sounds to me like python is not best choice to implement this then

We are moving forward with the proposed divide and conquer strategy.

**Comment by marcus1487** [comment]
The updates in the latest release (2.3.0) should help resolve the issue found here. Please re-open this if issues persist.
