### ISSUE TITLE
per_read_mods interpretation

### ISSUE THREAD

**Issue by PaulaRomeroLozano** [nanoporetech/megalodon#101]
Hi Marcus,
I have run megalodon using res_dna_r941_min_modbases_5mC_v001.cfg.
I have got as outputs:  "basecalls", "mappings", "mod_mappings", "mods", "per_read_mods (.txt and .bd)"
I would like to double-check how to interpret, for instance, the “per_read_mods” output file. Please find the table below:

![image](https://user-images.githubusercontent.com/62566311/108708925-5ae8cf00-7512-11eb-990f-d3ad31590ffc.png)
 
Am I right in saying that in order to find out whether a base is methylated or canonical, I have to get the Absolute log ratio = |mod_log_prob|-|can_log_prob|  ?
And so, if I set up my threshold to be 2; 
Absolute log ratio ≥ 2  confident that it is a methylated base
Absolute log ratio ≤ - 2  confident that it is a canonical base
Once that it’s been verified, I could from this file get information regarding frequencies and methylation sites profile, right?
If you could bring some light on this it would be amazing!

Thank you very much in advance,
Regards,

Paula

**Comment by marcus1487** [comment]
This is mostly correct, but megalodon does not use the log ratio statistic. This decision was made in order to more robustly handle models with more than one modified base (e.g. 5mC+5hmC model).

Megalodon uses a threshold on the modified base probability. By default a modified/canonical call is only counted when the probability is >0.8. With only one modified base this translates to a log ratio threshold of ~1.39. This threshold can be set with the `--mod-binary-threshold` argument to either the `megalodon` or `megalodon_extras aggregate run` commands.

This is the computation stored in the `mods` output (bedmethyl file by default).
