### ISSUE TITLE
Call Tab delimited from bam ?

### ISSUE THREAD

**Issue by tonperre** [nanoporetech/megalodon#104]
Hi,

I'm very excited to use Megalodon, thanks for the amazing job developing it.
I have bam and mod bam files that I didn't produced myself but I would like to transform them in a tab delimited to have the methylation calls probability.
I don't have so far guppy install because I can't access the resource center. I tried following the doc (https://nanoporetech.github.io/megalodon/file_formats.html#tab-delimited) to get the files from the bam mod using the flag --write-mods-text

I have tried a lot of combinations around `megalodon [file] --write-mods-text`
but it always complains for the absence of Guppy 

1. Is it possible to convert a mod bam in tab delimited without going for the full run again?
2. Is guppy needed at this stage?
3. If yes : what are the possibilities to download and install guppy ? 

Thanks a lot,

**Comment by marcus1487** [comment]
1. Megalodon does not come with a tool to convert the mod bam into a tab delimited file without re-running the command. The mod bam file is seen as a terminal output from megalodon. The megalodon mods database file can be converted into the tab delimited output as this is an intermediate output (see the `megalodon_extras per_read_text modified_bases ` command). 
2. Guppy would be needed at this stage for the basecalling backend.
3. Please contact technical support in order to inquire about acquiring a guppy installation.
