### ISSUE TITLE
--mod-motif m CG 0 vs Z CG 0

### ISSUE THREAD

**Issue by JWDebler** [nanoporetech/megalodon#109]
Hi,
Can someone tell me why sometimes `m CG 0` and other times `Z CG 0` is mentioned in the documentation? And, does it make a difference?
Thank you.

**Comment by marcus1487** [comment]
When the first modified base models were released there was no community standard for modified base single letter codes. Thus we started naming modified bases from the end of the alphabet (as an arbitrary convention). Since the release of these first models the hts-specs group has provided a [draft community standard for modified base notation and bam format storage](https://github.com/jkbonfield/hts-specs/blob/methylation/SAMtags.tex#L532). This standard will be followed in all foreseeable future modified base model releases.

In order to interrogate the modified bases available from a particular model the `megalodon_extras modified_bases describe_alphabet`  command is available. Note though that models using the `Z` single letter code are out of date and better models from Rerio should be used instead.
