### ISSUE TITLE
mappings.bam cannot be indexed

### ISSUE THREAD

**Issue by fidibidi** [nanoporetech/megalodon#114]
Hello!

I run 
'/home/ec2-user/.pyenv/versions/3.6.0/bin/megalodon fast5/ --outputs basecalls mappings --guppy-server-path guppy/ont-guppy-cpu/bin/guppy_basecall_server --reference GRCh38_no_alt.fa --output-directory meg-out2/ --overwrite'

and it gives me the output I asked for, however the mappings.bam file doesn't have an index? 

I try to run samtools on it, and am given this error:
`Read '327fa795-ff84-46f3-8c57-c168c01beebd' with ref_name='chr5', ref_length=181538259, flags=0, pos=115163518 cannot be indexed
samtools index: failed to create index for "mappings.bam"`

Any ideas where my issue may lie? 

Thanks!

**Comment by marcus1487** [comment]
Only sorted bam files can be indexed. Have you sorted the mappings bam file first?

Also note that megalodon can perform sorting and indexing using the `--sort-mappings` flag. See discussion on this in another recent issue: https://github.com/nanoporetech/megalodon/issues/113#issuecomment-791724385

See notes on this issue here: https://github.com/samtools/samtools/issues/1182

**Comment by fidibidi** [comment]
Marcus!

Was about to close my issue because I also realized this was my mistake... Haha!

Thanks for the quick response!
