### ISSUE TITLE
Degenerate bases and megalodon

### ISSUE THREAD

**Issue by JosephLalli** [nanoporetech/megalodon#13]
Hello!

I've got an idea that I think would work, but I need your help. 

[https://www.biorxiv.org/content/10.1101/645903v1](url) 

I'm trying to replicate this paper's results using patterned UMIs. These UMIs are regions of my primers that have unknown sequences but known length (18bp) and known restrictions on possible sequences ("NNNYRNNNYRNNNYRNNN"). Each UMI is flanked by a known 20bp sequences, making the region easy to identify.

Accurate per-read basecalling of these regions is critical. It seems to me that we should be able to use the pattern to aid basecalling. (In other words, we should be able to answer the question 'Over a given series of observed events, what is the most likely sequence that fits the UMI pattern?')

Do you think megalodon could help here? I've tried making a vcf file of my UMI but I don't know if I did it appropriately for megalodon.

Best,
Joe

**Comment by marcus1487** [comment]
Megalodon should be able to assist in this task, though it might not be a perfect solution. The trouble is that megalodon does not support mapping to sequence with ambiguity codes (and I'm not really sure how this would proceed). Thus I would suggest using a single valid version of the UMI as the reference and then providing all possible alternatives via the VCF file. 

The particular reference sequence chosen will certainly have some effect on the results which is the part which is not ideal, but some adjustments can be made to minimize this effect. The main effect that the reference sequence will have is on the signal mapping to the reference sequence. In order to address this the `--variant-context-bases` threshold should be increased. The default setting for single base swaps is `15`, increasing this to 20-25 would likely improve the results here.

The second parameter that could be adjusted is actually hard coded in the megalodon code. In a future release this parameter may be made available via the command line. This parameter controls the number of variants that are considered in potential coordination with any particular variant. This parameter is set to 16, but could be set to a higher value in order to compute statistics over more possible context sequences (at the cost of higher compute cost). This parameter is set [here in the code](https://github.com/nanoporetech/megalodon/blob/master/megalodon/variants.py#L1481) and could be changed and the software re-installed in order to adjust this parameter.

Most likely, the least accurate portions after this analysis will be towards the center of the UMI as the chosen reference sequence will dictate the signal assignment and sequence alignments. There are potential avenues to improve the results, but would involve some custom scripting. The megalodon API (though currently undocumented) might be helpful here, but will likely require a lot of extra effort and would likely be beyond the scope of the main megalodon release. One of these avenues would be to take the basecalls from the UMI and use the megalodon framework to propose insertions or deletions to correct the length of the sequence followed by proposed sequence variants in order to polish the sequence. If this is of interest the relevant portion of megalodon code related to this processing can be found [here](https://github.com/nanoporetech/megalodon/blob/master/megalodon/variants.py#L608).
