### ISSUE TITLE
Is dna_r9.4.1_450bps_modbases_5mc_hac.cfg the same as 5mC in all context model from Rerio repo?

### ISSUE THREAD

**Issue by PanZiwei** [nanoporetech/megalodon#130]
Hi,
1. You mentioned that  "By default, Megalodon uses the `dna_r9.4.1_450bps_modbases_5mc_hac.cfg` Guppy config (released in version 4.5.2). This config is compatible with DNA, R9.4.1, MinION/GridION reads and allows output of 5mC calls in all contexts. Use the --guppy-config option to specify a different guppy model config. The appropriate Rerio model is recommended for the highest accuracy modified base calls."
But in the Rerio repo there is two config on R9.4.1 5mC in all context model: `res_dna_r941_min_modbases_5mC_v001.cfg`, `res_dna_r941_prom_modbases_5mC_v001.cfg` tested on Guppy v4.2.2.
So, what is the relationship between these 3 cfg model: res_dna_r941_min_modbases_5mC_v001.cfg, res_dna_r941_prom_modbases_5mC_v001.cfg, dna_r9.4.1_450bps_modbases_5mc_hac.cfg?

2. You mentioned that "The new models show significantly better 5mC detection performance than the mod base models found in guppy <4.5.2" in https://github.com/nanoporetech/megalodon/issues/125#issuecomment-809689795. 
So will there be much difference between the results between **Megalodon v2.2.9 with Guppy v4.2.2 and base called model res_dna_r941_min_modbases_5mC_v001.cfg from Rerio**  and **Megalodon v2.3.1 with Guppy v4.5.2 default model dna_r9.4.1_450bps_modbases_5mc_hac.cfg**?

**Comment by marcus1487** [comment]
These three models are the exact same as the ones in Rerio. Models are initially released in Rerio. Then as models are more thoroughly validated they are transferred into Guppy. Note that in the megalodon calibration files directory these three models actually link to the corresponding Rerio models (to save on the size of the repo and make the link explicit).

Since these are the same models there will be essentially no difference in the results between using these two settings.

**Comment by Modernism-01** [comment]
I also want to know the difference with "dna_r9.4.1_450bps_modbases_5mc_hac_prom.cfg" if I select the config "dna_r9.4.1_450bps_modbases_5mc_hac.cfg". My sequencing device is PromethION. Or I will get the same output using two different config file?
