### ISSUE TITLE
mod-aggregate-method, which to choose?

### ISSUE THREAD

**Issue by ruicatxiao** [nanoporetech/megalodon#157]
Hi! 

I have been applying all context modification on a set of microbial data. In order to detect novel modification motif I am trying to increase the modification calling stringency. I see for the flag mod-aggregate-method there are two options: expectation_maximization and binary_threshold. binary_threshold allows setting of alternative thresholds while the other one does not. I went through the entire documentation hoping to find detailed explanation between the two but could not find any. Could you provide some insights on these two options and which one to use?

Thanks!

**Comment by marcus1487** [comment]
Hi @ruicatxiao ,

The `expectation_maximization` setting was added as an experimental research project and left in simply since it was easier than stripping it out. It is not documented anywhere, but you can see the [core implementation in the code here](https://github.com/nanoporetech/megalodon/blob/master/megalodon/mods.py#L2676). This method was intended to produce more robust calls than the binary threshold, but the result were not as good, so it is not recommended.

The `binary_threshold ` aggregation method is the recommended method. This method defines a region of uncertainty based on the per-read modified scores. Uncertain probabilities do not contribute to the reported fraction of modified bases at a reference site. Thus only confident per-read scores will contribute to the reported fraction. Increasing the `--mod-binary-threshold` parameter (default `0.8`) will increase the stringency of the calls included, but will exclude more calls from the reported fractions.

**Comment by ruicatxiao** [comment]
Amazing answer as always. Thank you!

Are there specific megalodon major publication source we can cite on? I have seen a lot of the internal comparisons between megalodon and WGBS. Would be nice to be able to cite those comparisons in a publication format.

**Comment by marcus1487** [comment]
Thank you!

Unfortunately, we do not currently have an internal publication on nanopore methylation benchmarking.
