### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by brucemoran** [nanoporetech/megalodon#18]
Any plans for a conda package?

**Comment by marcus1487** [comment]
Yes. The only issue is the current taiyaki soft-requirement (which will likely not make it onto conda given the cuda/gpu settings, handled via make install procedure). With the new guppy `--post_out` option taiyaki is no longer strictly required, so a conda release likely makes sense at this point.

**Comment by brucemoran** [comment]
Cool, didn't want to go through install specifically because of taiyaki, glad there will be a guppy option.

Look forward to it whenever it happens!

**Comment by marcus1487** [comment]
Sorry for the poor wording. The guppy mode is available in the current release. This option allows megalodon to run from the fast5 files output from guppy with the `--post_out` option specified. Note that the `--post_out` option can increase the fast5 file size by 5-10X and force guppy to run much slower due to disk I/O. Thus this is not the long term solution, but a stopgap. We hope to have guppy basecalling integrated into megalodon in a future release as the long term solution. As of right now though, the taiyaki install is not strictly required, so the conda package will just involves me putting together and submitting the conda recipe.

**Comment by brucemoran** [comment]
Yes, my fault just re-read the docs now and see it is already stated that Guppy can be used (I thought it was only taiyaki, not sure where I got that idea).

Speed not super important as it's only a pilot study, hence my not really wanting the headache of installs (already have a singularity/conda recipe with Guppy and other ONT-related tools so slotting in there would be fine).

Thanks for the replies, much appreciated.

**Comment by marcus1487** [comment]
Conda package added (https://github.com/bioconda/bioconda-recipes/pull/20570). Should be in the conda public distro in the next day.
