### ISSUE TITLE
Proper guppy config file for MinION methylation

### ISSUE THREAD

**Issue by cstill3928** [nanoporetech/megalodon#222]
Hi,

Sorry if this has been asked but I couldn't find an issue which helped clarify this nor could I really figure this out from the [rerio github page](https://github.com/nanoporetech/rerio). I'm trying to do methylation calling from LRS data generated with a R10.3 flowcell in the MinION Mk1C.  When I checked the configuration files available for use with Megalodon I got the following output:

![Screen Shot 2021-11-30 at 1 48 44 AM](https://user-images.githubusercontent.com/73316343/144024246-e3e608b7-d4d6-4368-8f9c-e6af4902949b.png)

From this output, it seems that the best configuration to use is "dna_r10.3_450bps_modbases_5mc_hac_prom.cfg"  as it has modbase support and is for r10.3. However it has the "prom" tag specifying it for use with data generated on the promethION. So which configuration file would be best for methylation calling with a r10.3 flowcell on the MinION Mk1C?

Thanks,
Chris

**Comment by marcus1487** [comment]
You are correct that this model (`dna_r10.3_450bps_modbases_5mc_hac_prom `) would be the recommendation for minion and promethion data on R10.3. There is very little difference between the currently released promethion and minion flowcells in terms of the signal, so going forward minion and promethion models will be interchangeable. The difference was due to legacy minion flowcells which showed slightly different signal characteristics and thus different models to achieve the highest accuracy. I hope this helps clarify and please reach out if you have further issues.
