### ISSUE TITLE
[Question] Does using Megalodon for just mappings make sense? 

### ISSUE THREAD

**Issue by fidibidi** [nanoporetech/megalodon#237]
Hi All!

Apologies if this is a confusing statement, what I mean moreso:

If I have a project that only needs FAST5s to be mapped to BAM, is it any different to use Megalodon vs just doing

Guppy for basecalling > minimap2 for alignment? 

Since, if I'm not mistaken, this is the logic that Megalodon uses? 

thanks!

**Comment by marcus1487** [comment]
Yes. This is functionally the same thing (save for mismatching versions of guppy inside megalodon version). Note also that guppy can directly produce mappings (though you'll have less control of the minimap2 version there). Either megalodon or guppy can be used for this purpose. This feature was included in megalodon since previous versions of guppy did not support read mapping. I hope this helps, but please comment with any further clarifications.

**Comment by fidibidi** [comment]
Perfect, 
Thanks!!!
