### ISSUE TITLE
How to run megalodon without guppy?

### ISSUE THREAD

**Issue by wangzhennan14** [nanoporetech/megalodon#240]
Hi,
    I recently learned to run megalodon, but I have run guppy (version=5.0.11) with my data. Do I  need to run guppy again when I run megalodon? Or I just run minimap2 and  megalodon, could you please give me some sugesstion? Thank you very much!
     Best wishes,
     wangzhennan

**Comment by marcus1487** [comment]
Megalodon requires the "move table" which contains the mapping between the raw signal and the basecalls for a read. This is produced by the basecaller, but not currently stored in the output of Guppy. Without this information Megalodon cannot produce the results related to the signal. This is why megalodon runs Guppy as the basecalling backend. We are working on solutions to avoid this in the future, but with the current software versions Megalodon must run Guppy again (within Megalodon).

**Comment by sklages** [comment]
@marcus1487  -- just curious: has this been implemented with `--do-not-use-guppy-server`? 
Instead of having `guppy`to recall the data, I'll provide fast5 data from a previous `guppy`run (with `--post_out`).
Did I get it right or am I terribly wrong?

**Comment by MariameCoulibaly26** [comment]
HI, I'm trying to run megalodon but I don't want to run guppy basecaller with it. Because I already have the reads from guppy basecaller that I have run separately. So is there a way to disable the "basecalling step by guppy". Also, when I try to run megalodon with the precise path --guppy-basecall-server, I have this error: ERROR: Guppy server initialization failed. See guppy logs in [--output-directory] for more details.
		Try running the guppy server initialization command found in log.txt in order to pinpoint the source of this issue.
Thanks.

**Comment by marcus1487** [comment]
Unfortunately, megalodon does not have support for running on basecalls as input. This is mainly due to the fact that the "move table" (mapping between the signal and basecalls) was only recently added as an optional output into the basecalling output. Without this mapping megalodon cannot call modified bases. Unfortunately megalodon will not add support for this new tag as megalodon is being deprecated. It is recommended that modified base calls be obtained from the production basecallers (guppy or minknow for the GUI interface) now.

In the future it may be possible to call modified bases (given that the new move table tag was selected) directly using the remora repo, but this will likely remain a research feature.

**Comment by MariameCoulibaly26** [comment]
Ok thank you.
But what can I do to make it work? I have this error in the guppy-server log file : 
/builds/ofan/ont_core_cpp/ont_core/common/cuda_common.cpp:136: CUDA_ERROR_NO_DEVICE
Does this mean that I have to install CUDA? I'm a little confused.

**Comment by marcus1487** [comment]
It appears that your system does not have CUDA installed for GPU capabilities. If you do not have GPU resources then you should install the CPU version of Guppy, but not that it will be very slow.
