### ISSUE TITLE
Create modified_bases.5mC.bed while liveprocessing

### ISSUE THREAD

**Issue by m0nib** [nanoporetech/megalodon#263]
HI,

Can Megalodon be setup to create modified_bases.5mC.bed while it is processing live acquisition run.

At the moment modified_bases.5mC.bed is only being generated at the end of the run, i.e. when final_summary_* file has been generated.

Thanks
Monib

**Comment by marcus1487** [comment]
The aggregated bed file cannot be produced while processing is ongoing as it is an aggregation across reads at each reference site. Thus each line in the output bed file hit by a new read during processing would have to be updated for each new read. This would be an incredibly inefficient process (or consume a potentially very large amount of memory). In fact in order to make the aggregation step reasonably efficient the modified base database must first be indexed by reference position. This also cannot be done until the database writes are complete (or would need to be re-run when any new reads were added). 

The best solution may be a checkpoint aggregation step. This would involve copying the database file during the run and completing the database indexing and aggregation on the checkpoint database (I can't guarantee that the copied database will not be corrupted if this copy is performed during a database write operation). The commands to try this would be `megalodon_extras modified_bases index_database` and `megalodon_extras aggregate run`. If this does not work I would unfortunately say that this is out of scope for the megalodon project.

**Comment by m0nib** [comment]
Hi @marcus1487 

thank you for the useful info. Just another quick question, is it possible to use modbam2bed to convert the generated ban file to bed file? As I have tried it and it seems to work. However modbam2bed gives extra CpGs, so I was wondering what parameter could I use to match the output bed file from megalodon. 

Thank you
Best
Monib

**Comment by m0nib** [comment]
hi @marcus1487 ,

I tried your suggestion of running megalodon_extras aggregate run command, but i keep getting the following error:

FileNotFoundError: [Errno 2] No such file or directory: '/home/vml/megalodon_result/Bench_NumReads/megalodon/megalodon_results/log.aggregation.re_aggregated.txt'


I have checked few times during the main megalodon run there is no folder being created ./megalodon_results
