### ISSUE TITLE
Feature request: resume mode

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/megalodon#271]
I am trying to run megalodon on a huge sequencing run on our HPC cluster, but there is a maximum job time. Eg. megalodon will take 5-6 days but the maximum job time is 2.

Is there a way to have a resume mode or does it already exist? That way I can queue the job up several times so that it will eventually finish.

**Comment by marcus1487** [comment]
This is unfortunately there is not a way to resume a megalodon run and it is quite a large feature to add reliably (mostly due to safety of the modified bases database). 

For runs that take a long time, I would highly recommend processing subsets of the data and merging required outputs (e.g. `samtools merge` for mapping formats). The megalodon run can be run on subsets without copying the raw data with softlinks for a subset of fast5s to a new directory.
