### ISSUE TITLE
Result about Megalodon

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/megalodon#283]
Hi, after running megalodon command, it generated 'mod_mappings.bam' and 'per_read_modified_base_calls.txt'. I compute the total CG number from these two files separately, 'Ml' flag from mod_mappings.bam and just the rows of per_read_modified_base_calls.txt, but get the different results and I do not know why. The number from .bam is larger than the number from .txt.

Which file should I use?

**Comment by marcus1487** [comment]
These two outputs should match. How are you going about extracting the "total CG number" from each file? Also what commands were run to generate the files. Are you using the 5mC model or 5mC+5hmC?

**Comment by Flower9618** [comment]
Thank you very much for your reply. I am using the 5mC model. For .bam, I detected 'Ml' tag and count the number of scores reported after 'Ml'. For .txt, I just counted the number of lines in the file.

**Comment by marcus1487** [comment]
I had a look and this is due to a filter applied to the per-read results. Specifically the `--edge-buffer` parameter (see `megalodon --help-long` for more details). This filters modified base calls near the edge of a read before entering them into the database (or per-read text file), but after inserting them in the mod_mapping output. This is done in the code [here](https://github.com/nanoporetech/megalodon/blob/master/megalodon/mods.py#L1764). This `--edge-buffer` parameter has been set to `0` in the latest release to avoid this type of confusion and has shown to have minimal effect with more recent Remora modified base calling. Thus updating megalodon should make these results correspond exactly.
