### ISSUE TITLE
RNA  methylation config file

### ISSUE THREAD

**Issue by qhli1** [nanoporetech/megalodon#29]
Hello,  I want to identify RNA methylation. But the config file, dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac_prom.cfg, is for DNA rather than RNA when basecalling. I tried to use rna_r9.4.1_70bps_fast.cfg. But it did not work because of no methylation information in the file.  Therefore, I want to know how to set the config option ( --guppy-config) for the identification of RNA methylation? Thanks!

**Comment by marcus1487** [comment]
There is not yet a basecalling model for the specific detection of RNA modified bases. This is an activate area of internal research.

Signal-level investigation of RNA modified bases can currently be completed with Tombo.

**Comment by qhli1** [comment]
Thanks for your explanation. So, we cannot use megalodon to detect the RNA methylation?

**Comment by marcus1487** [comment]
Megalodon is capable of processing and outputting RNA methylation results given an RNA basecalling model trained for specific modified base detection. The issue is that such a model has not yet been released. 

One could train their own modified base RNA model using the Taiyaki software package. The next Megalodon release will have more capabilities and documentation concerning training modified base models.

RNA methylation is an area of active research internally and we hope to have an RNA methylation basecalling model released as soon as possible, though there is not a firm timetable for such a release at this time.
