### ISSUE TITLE
Question about the setting of “--processes"

### ISSUE THREAD

**Issue by DAVID2022** [nanoporetech/megalodon#3]
If I use  48 core xeon cpu with dual NVIDIA Tesla V100 and 500GB RAM  to process  ONT fast5 data with megalodon，how many ”--processes“ should I set to use the full power of my computer and speed up the process of analysis?

**Comment by marcus1487** [comment]
In order to achieve the best performance from megalodon using a setup with GPUs one should aim to saturate the GPU memory as much as possible. With both V100s in use (`--devices 0 1`) the aim should be to set the processes argument to make full use of the GPUs. For each `--processes` that is set, a new copy of the model must be loaded on the GPU. I have generally found that the model takes ~500MB of GPU space, but some trial and error may be necessary to dial in the exact compute setup that works best on your resources.

Note that basecalling speed is significantly (~5X) slower than using guppy at the moment, but we are working to increase this speed within the megalodon framework.

**Comment by DAVID2022** [comment]
Thank you very much, I will try those setting now!
