### ISSUE TITLE
Question about modification model accuracy and compatibility

### ISSUE THREAD

**Issue by Yuri3003** [nanoporetech/megalodon#36]
Hi,
How accuracy can megalodon be when using the res_dna_r941_min_modbases_5mC_5hmC_CpG_v001 and res_dna_r941_min_modbases-all-context_v001 model to extract all context 5mc methylation and 5hmc methylation information? Have you ever tested those models before release them? If you have, can you show me your benchmark data? So that I can be confident in using those models in my research project. 

As I want to extract 5hmc methylation information and 5mc methylation information on CHH and CHG motif using PromethION data, what should I do to make res_dna_r941_min_modbases_5mC_5hmC_CpG_v001 and res_dna_r941_min_modbases-all-context_v001 model (which were trained for MinION/GridION data, lack PromethION version ) suitable for my PromethION data ?

**Comment by marcus1487** [comment]
Hi @Yuri3003 , This issue has been logged in #9 . 

These models listed have been released via the Rerio repository which contains "research release" basecalling models. Specifically, this means that these models have not undergone more thorough testing and validation as production release basecalling models. We believe these models have good utility, and thus wanted to get them to users as fast as possible. If one would like to run models with such validation and support guarantees I would recommend using the models shipped with the production Guppy basecaller.

For a current status of the benchmarking issue, we are working towards a more comprehensive benchmarking for a range of models, but do not currently have a framework for the comprehensive evaluation of models. This will be even more complicated for modified bases, as new validation datasets will need to be generated for new modified bases (e.g. 5hmC).

For the final question involving models for a specific set of run conditions, we will work towards creating models for a range of platforms, but will release models as they have been trained to sufficient performance. While MinION/GridION and PromethION show similar signal level characteristics they are different enough that accuracy is improved with separate model training. The accuracy drop is exaggerated for modified bases which generally involve much smaller shifts in signal. Depending on your larger biological question, there may be some utility to using these models on PromethION data, but given the research release model, this is left for users to determine.

I hope this information helps and I wish you the best in your research goals!

**Comment by Yuri3003** [comment]
Thank you very much for your kind help !

Can I extract CHG  context methylation information by using megalodon like:"
megalodon raw_fast5s/ \
    --guppy-config res_dna_r941_min_modbases-all-context_v001.cfg \
    --outputs  mods \
    --reference reference.fa  \
    --mod-motif Z CHG 0 --devices 0 1 --processes 100 \
    --verbose-read-progress 3
"

Can I build motif-specific model from ground truth data (WGBS result)  using megalodon?  Like the way you mentioned in https://nanoporetech.github.io/tombo/tutorials.html#build-motif-specific-model-from-ground-truth.

**Comment by Yuri3003** [comment]
Thank you very much for your kind help !


--


岳阳

Yang Yue

****************************************************

Add :  No.2,West Yuanmingyuan Road,Haidian District, Beijing,PRC,100193

Mobile:131－2671－9887

Email:  13126719887@163.com

-----------------------------------------------------

China Agricultural University
College of Agriculture and Biotechnology

Department of Plant Genetics and Breeding

****************************************************

On 6/22/2020 21:27，Marcus Stoiber<notifications@github.com> wrote：

Hi @Yuri3003 , This issue has been logged in #9 .

These models listed have been released via the Rerio repository which contains "research release" basecalling models. Specifically, this means that these models have not undergone more thorough testing and validation as production release basecalling models. We believe these models have good utility, and thus wanted to get them to users as fast as possible. If one would like to run models with such validation and support guarantees I would recommend using the models shipped with the production Guppy basecaller.

For a current status of the benchmarking issue, we are working towards a more comprehensive benchmarking for a range of models, but do not currently have a framework for the comprehensive evaluation of models. This will be even more complicated for modified bases, as new validation datasets will need to be generated for new modified bases (e.g. 5hmC).

For the final question involving models for a specific set of run conditions, we will work towards creating models for a range of platforms, but will release models as they have been trained to sufficient performance. While MinION/GridION and PromethION show similar signal level characteristics they are different enough that accuracy is improved with separate model training. The accuracy drop is exaggerated for modified bases which generally involve much smaller shifts in signal. Depending on your larger biological question, there may be some utility to using these models on PromethION data, but given the research release model, this is left for users to determine.

I hope this information helps and I wish you the best in your research goals!

**Comment by marcus1487** [comment]
That command will indeed extract all CHG context 5mC calls. If you are interested in all 5mC contexts (CpG, CHH and CHG) I would recommend calling with no `--mod-motif` and processing the results with a motif-specific filters (in order to save the compute required for markup of each context separately). For example, a bed file with results for all contexts can be provided to the `megalodon_extras validate results` command along with a number of bed files for the separate sequence contexts via the `--valid-sites` argument.

For the second question, yes Megalodon supports modified base model training from motif ground truths. See [the docs here](https://nanoporetech.github.io/megalodon/modbase_training.html). Note though that this is not quite as simple as training from a WGBS results. As with Tombo, a per-read markup is required. The Tombo and Megalodon commands will markup all sites matching a sequence motif of interest. Markup up results from a WGBS results at a per-read level is a bit more complicated. We are working on methods for such markup internally, but do not have anything robust enough for release at this time.

**Comment by DAVIDEE3** [comment]
So，can I extract CHG context methylation information by using megalodon like:"
megalodon raw_fast5s/ \
--guppy-config res_dna_r941_min_modbases-all-context_v001.cfg \
--outputs mods \
--reference reference.fa \
--devices 0 1 --processes 100 \
--verbose-read-progress 3

megalodon_extras validate results \
--valid-sites CHG-position.bed  \
megalodon_results_dir
"

**Comment by Yuri3003** [comment]
So，can I extract CHG context methylation information by using megalodon like:"
megalodon raw_fast5s/
--guppy-config res_dna_r941_min_modbases-all-context_v001.cfg
--outputs mods
--reference reference.fa
--devices 0 1 --processes 100
--verbose-read-progress 3

megalodon_extras validate results
--valid-sites CHG-position.bed
megalodon_results_dir
"

**Comment by Yuri3003** [comment]
So，can I extract CHG context methylation information by using megalodon like:"
megalodon raw_fast5s/ \
--guppy-config res_dna_r941_min_modbases-all-context_v001.cfg \
--outputs mods \
--reference reference.fa \
--devices 0 1 --processes 100 \
--verbose-read-progress 3

megalodon_extras validate results \
--valid-sites CHG-position.bed \
megalodon_results_dir
"

**Comment by Yuri3003** [comment]
So，can I extract CHG context methylation information by using megalodon like:"
megalodon raw_fast5s/ \
--guppy-config res_dna_r941_min_modbases-all-context_v001.cfg \
--outputs mods \
--reference reference.fa \
--devices 0 1 --processes 100 \
--verbose-read-progress 3

megalodon_extras validate results \
--valid-sites CHG-position.bed \
megalodon_results_dir
"

**Comment by marcus1487** [comment]
Sorry for the confusion concerning all context. I meant to note that if you would like to extract modified base calls at all cytosine contexts, but later analyze these for CpG, CHH and CHG separately, that the output from the initial megalodon command should be output from a single megalodon run (and thus into a single file). The reason here is that each time megalodon is run the raw signal must be basecalled again; so it would be very computationally expensive to run megalodon 3 times in order to obtain the three separate CpG, CHH and CHG context output files. 

If these three context-dependent BED files are required I would suggest using a third-party tool such as bedtools (e.g. [bedtools intersect](https://bedtools.readthedocs.io/en/latest/content/tools/intersect.html)) to extract the separate output files. The example megalodon_extras command is an example within the Megalodon framework for how to analyze data without separating the results into a single file for each sequence context.

**Comment by Yuri3003** [comment]
Thank you very much for your kind help ! I will try your great software on my data now!
