### ISSUE TITLE
Error in Aggregation 

### ISSUE THREAD

**Issue by Naish-M** [nanoporetech/megalodon#37]
Hi
I was running Megalodon on a set of reads but once it passed the indexing step I got the following error:
[16:39:39] Waiting for mods database to complete indexing.
Traceback (most recent call last):
  File "/home/group/.local/bin/megalodon", line 11, in <module>
    load_entry_point('megalodon==2.1.0', 'console_scripts', 'megalodon')()
  File "/home/group/.local/lib/python3.6/site-packages/megalodon/__main__.py", line 361, in _main
    megalodon._main(args)
  File "/home/group/.local/lib/python3.6/site-packages/megalodon/megalodon.py", line 1105, in _main
    mods_info.mod_output_fmts, args.suppress_progress_bars)
  File "/home/group/.local/lib/python3.6/site-packages/megalodon/aggregate.py", line 302, in aggregate_stats
    agg_mods = mods.AggMods(mods_db_fn, no_indices_in_mem=True)
  File "/home/group/.local/lib/python3.6/site-packages/megalodon/mods.py", line 2040, in __init__
    self.mods_db = ModsDb(mods_db_fn)
  File "/home/group/.local/lib/python3.6/site-packages/megalodon/mods.py", line 149, in __init__
    self.establish_db_conn()
  File "/home/group/.local/lib/python3.6/site-packages/megalodon/mods.py", line 197, in establish_db_conn
    self.db.execute('PRAGMA cache_size = {}'.format(-mh.SQLITE_CACHE_SIZE))
sqlite3.OperationalError: attempt to write a readonly database

This seems odd that it was able to write to the database in the previous step but then encountered an error. I then manually changed the permissions to allow all read and write and tried to run 'megalodon_extras aggregate run --outputs mods' and still get the same error. 

Any advice on this would be greatly appreciated.

**Comment by marcus1487** [comment]
I have not seen this behavior previously, so I'm guessing this has something to do with a specific sqlite settings/versions in your environment (this doesn't help resolve the issue though). This looks like an issue similar to [this one](https://stackoverflow.com/questions/17793672/perl-dbi-treats-setting-sqlite-db-cache-size-as-a-write-operation-when-subclassi), which indicates some relation to transaction tracking. You might consider setting `--database-safety 0` (I've actually considered making this the default).

For background on the issue, this occurs on a new connection to the database from the one established for saving the data. This connection is actually established in order to extract some minimal information before spawning the aggregation processes (see [here](https://github.com/nanoporetech/megalodon/blob/master/megalodon/aggregate.py#L302)). The specific error is also a bit odd since this is setting a PRAGMA (general SQLITE setting) which is not a write operation. This setting likely does not help with readonly connections in any case, so I will more this specific call into the section for writing database connections in order to avoid this type of error in the future.

**Comment by marcus1487** [comment]
Also in order to complete the indexing step without completely starting the run over you can use this set of commands: https://github.com/nanoporetech/megalodon/issues/16#issuecomment-642764659

I will look into making this a part of the `megalodon_extras` commands as well.

**Comment by Naish-M** [comment]
Hi Marcus,
Thanks, running with --database-safety 0 does solve the read-only error. 
However, the database it generates is large (320Gb) so the indexing fails (using the commands above) even when run on a 500Gb node. So to make it more manageable I wish to restrict the methylation to only C's (but in all context, CG, CHG, CHH) when I'm using the res_dna_r941_min_modbases-all-context_v001.cfg I just wanted to check if "--mod-motif Z C 0" would be appropriate with this model. 

Full command:
megalodon /media/group/data/Fast5_10kb_88% --outputs mods --reference /home/group/ref.fasta --devices cuda:0 --processes 8 --guppy-server-path /home/group/ont-guppy/bin/guppy_basecall_server --overwrite --guppy-params "-d /home/group/rerio/basecall_models/" --guppy-config res_dna_r941_min_modbases-all-context_v001.cfg --database-safety 0 --mod-motif Z C 0

**Comment by marcus1487** [comment]
Hi @Naish-M ,

Yes, the `--mod-motif Z C 0` is the correct setting in order to restrict to only 5mC calls. This should reduce the mods database memory requirements by about half.

The next release will include further reductions in the size of this database.

**Comment by Naish-M** [comment]
Hi @marcus1487, 
Thanks. I was looking through the log file produced for my last run and there are a number of instances of:

DBG: mods:1265: Insufficient blocks to compute mod score at Chr:-----  got x and need y
and this isn't flagged within the run output - and occurs primarily in longer reads 

I'm guessing a memory issue? Would this be RAM or the GPU memory? 

Also, I notice that the position can change in these errors (see below) - so is megalodon aligning each base location separately? as this could cause errors in the aggregation especially if the read spans repetitive regions.

DBG: megalodon: 275: Analyzing read 1ff918c2-39a1-4416-81aa-ae0822170b27
DBG: mods: 1265: Insufficient blocks to compute mod score at Chr4_RaGOO:42888 got 30 and need 31
DBG: mods: 1265: Insufficient blocks to compute mod score at Chr4_RaGOO:42891 got 25 and need 31
DBG: mods: 1265: Insufficient blocks to compute mod score at Chr4_RaGOO:42892 got 25 and need 31
DBG: mods: 1265: Insufficient blocks to compute mod score at Chr3_RaGOO:25762571 got 28 and need 31
DBG: mods: 1265: Insufficient blocks to compute mod score at Chr4_RaGOO:53237 got 22 and need 31
DBG: mods: 1265: Insufficient blocks to compute mod score at Chr4_RaGOO:53240 got 29 and need 31
DBG: mods: 1265: Insufficient blocks to compute mod score at Chr4_RaGOO:53243 got 29 and need 31
DBG: mods: 1265: Insufficient blocks to compute mod score at Chr4_RaGOO:63571 got 30 and need 31
DBG: mods: 1265: Insufficient blocks to compute mod score at ChrC_RaGOO:35657 got 24 and need 31
DBG: mods: 1265: Insufficient blocks to compute mod score at ChrC_RaGOO:35663 got 19 and need 31
DBG: mods: 1265: Insufficient blocks to compute mod score at ChrC_RaGOO:35669 got 25 and need 31
DBG: mods: 1265: Insufficient blocks to compute mod score at ChrC_RaGOO:35670 got 30 and need 31

**Comment by marcus1487** [comment]
This debugging warning was left in incidentally with this latest release (though it may be useful to leave in; it can just cause very large log file sizes). This indicates a likely genomic deletion around an intended modified base call. This could also be due to poor basecalls causing a large deletion, but most often this is the result of a genomic/reference deletion. When this happens there is no signal assigned to the region of reference sequence and thus there is no way to make a modified base call. 

This will result in missing modified base calls for these reads at these positions. If this is the result of a true genomic deletion these site will likely correspond across most all reads hitting this position.

As a larger point relevant here, the highest quality modified base calls will be obtained by processing reads with the highest quality reference. If there are errors in the mapped reference sequence then the modified base calls in the region may be adversely effected. I would recommend a step of polishing the reference sequence for the sample of interest, though I understand that collating results over many samples can be quite cumbersome computationally if this is done. This is simply the recommendation in order to obtain the highest quality modified base calls for a given sample.

**Comment by Naish-M** [comment]
Hi Marcus, Thanks for the info - yes does look like there are some structural variants in the reads compared to this position in the reference but also doesn't explain how the Chr location appears to change mid-read?

**Comment by marcus1487** [comment]
The log file is written  asynchronously across all processes. Thus the order of the last read listed as being analyzed and this debugging message may not correspond for multi-processing runs. If this debugging message is left in the log file it would likely be good to add the read id to this output (though this would inflate the file size further). I am leaning towards removing this line from the log at the moment.
