### ISSUE TITLE
--mod-motif Z CG 0 produces incorrect logging and output files

### ISSUE THREAD

**Issue by Shians** [nanoporetech/megalodon#38]
When running megalodon with `--mod-motif Z CG 0`, the logs state

```
Using canonical alphabet ACGT and modified bases Y=6mA (alt to A); Z=5mC (alt to C).
```

and produces an empty `modified_bases.6mA.bed` file.

It would also be nice to clarify what the Z and 0 indicate as it's not apparent from the documentation.

**Comment by marcus1487** [comment]
The alphabet information listed in the log is read from the model file. This line will be reported whenever this model is used. 

The `—mod-motif` option is provided in order to restrict the called modified sites for more efficient processing and lower output file sizes. Along these lines, when modified base output is requested, an output file is produced for each valid modified base from the model used. The reason the 6mA file is empty is that no mod motif is specified for 6mA. 

As for the values specified via the `—mod-motif` option, these values are 1) the modified base single letter code, 2) the canonical base motif (which can include ambiguity codes) and 3) the relative position of the modified base within the specified motif. The single letter codes available from a model can be determined by the `megalodon_extras modified_bases _describe_model` command.

**Comment by Shians** [comment]
I see, so the `Y=6mA (alt to A); Z=5mC (alt to C).` comes from a model file and `--mod-motif Z CG 0` should be interpreted as a post-filtering rather than specification of the model?

When I try to run `megalodon_extras modified_bases _describe_model` I get

```
usage: megalodon_extras modified_bases [-h]
                                       {describe_alphabet,estimate_threshold,update_database,create_ground_truth}
                                       ...
megalodon_extras modified_bases: error: argument action_command: invalid choice: '_describe_model' (choose from 'describe_alphabet', 'estimate_threshold', 'update_database', 'create_ground_truth')
```

**Comment by marcus1487** [comment]
Yes for the most part. The modified base specified in `--mod-motif` must exist in the provided model. But `--mod-motif` is a bit more than a post-filtering step. Processing and storing all-contexts modified bases can be quite computationally expensive, so filtering to a set of motifs of interest during a run has benefits beyond a simple filtering of results.

Apologies, I was typing the command from memory. The command I meant to type was `megalodon_extras modified_bases describe_alphabet`.

**Comment by Johnsonzcode** [comment]
Apologize,
`megalodon_extras modified_bases describe_alphabet` return below:
```
(megalodon) [poultrylab1@pbsnode01 ont_methylation]$  megalodon_extras modified_bases describe_alphabet -h
usage: megalodon_extras modified_bases describe_alphabet [-h]
                                                         [--log-directory LOG_DIRECTORY]
                                                         [--guppy-config GUPPY_CONFIG]
                                                         [--guppy-server-path GUPPY_SERVER_PATH]
                                                         [--guppy-logs-output-directory GUPPY_LOGS_OUTPUT_DIRECTORY]
                                                         [--do-not-use-guppy-server]
                                                         [--guppy-params GUPPY_PARAMS]
                                                         [--fast5s_dir FAST5S_DIR]
                                                         [--taiyaki-model-filename TAIYAKI_MODEL_FILENAME]

optional arguments:
  -h, --help            show this help message and exit
  --log-directory LOG_DIRECTORY
                        Directory to output megalodon log. Default: current
                        working directory.

Guppy Backend Arguments:
  --guppy-config GUPPY_CONFIG
                        Guppy config. Default:
                        dna_r9.4.1_450bps_modbases_5mc_hac.cfg
  --guppy-server-path GUPPY_SERVER_PATH
                        Path to guppy server executable. Default: ./ont-
                        guppy/bin/guppy_basecall_server
  --guppy-logs-output-directory GUPPY_LOGS_OUTPUT_DIRECTORY
                        Directory to output guppy logs. Default: guppy_logs
  --do-not-use-guppy-server
                        Use alternative basecalling backend. Either FAST5
                        (default; requires --post_out when running guppy) or
                        taiyaki (set `--taiyaki-model-filename` to use taiyaki
                        backend).
  --guppy-params GUPPY_PARAMS
                        Extra guppy server parameters. Main purpose for
                        optimal performance based on compute environment.
                        Quote parameters to avoid them being parsed by
                        megalodon.

FAST5 Backend Arguments:
  --fast5s_dir FAST5S_DIR
                        Directory containing raw fast5.

Taiyaki Backend Arguments:
  --taiyaki-model-filename TAIYAKI_MODEL_FILENAME
                        Taiyaki basecalling model checkpoint file.
```
No explanation for `1) the modified base single letter code`.

**Comment by marcus1487** [comment]
The `megalodon_extras modified_bases describe_alphabet` command needs to know which model is being run in order to describe the alphabet included in that model. New models (including user trained models with taiyaki) can be passed here and have alphabets of any type. In order to extract the alphabet from the `res_dna_r941_min_modbases-all-context_v001` model you have to specify the options for guppy to be able to use that model.

In the example output the `m=5mC (alt to C)` indicates all the information you desire. The `m` is the single letter code for `5mC` which is the long name for this modified base. In the parentheses it indicates this is an alternative base to `C`.

**Comment by Johnsonzcode** [comment]
I got it. Thank you very much indeed!
