### ISSUE TITLE
AssertionError when using modbases model

### ISSUE THREAD

**Issue by PengNi** [nanoporetech/megalodon#53]
Hi,

I want to call CpG methylation using the following command:
```shell
megalodon reads_fast5s/ \
    --guppy-server-path /opt/ont/guppy/bin/guppy_basecall_server \
    --guppy-params "-d ./rerio/basecall_models/ --num_callers 2" \
    --guppy-timeout 20 \
    --guppy-config res_dna_r941_prom_modbases_5mC_CpG_v001.cfg \
    --outputs mod_mappings mods \
    --reference $REF --mod-motif Z CG 0 \
    --write-mods-text \
    --mod-output-formats bedmethyl wiggle \
    --devices 3 --processes 20 --output-directory megalodon_results.CG \
    --overwrite > megalodon_results.CG.log 2>&1 &
```
However, it causes AssertionError:
```
File "/bin/megalodon", line 8, in <module>
    sys.exit(_main())
  File "/lib/python3.5/site-packages/megalodon/__main__.py", line 361, in _main
    megalodon._main(args)
  File "/lib/python3.5/site-packages/megalodon/megalodon.py", line 1074, in _main
    args, mods_info = parse_mod_args(args, model_info)
  File "/lib/python3.5/site-packages/megalodon/megalodon.py", line 918, in parse_mod_args
    mod_db_timeout=args.mod_database_timeout)
  File "/lib/python3.5/site-packages/megalodon/mods.py", line 1729, in __init__
    self._parse_mod_motifs(all_mod_motifs_raw)
  File "/lib/python3.5/site-packages/megalodon/mods.py", line 1637, in _parse_mod_motifs
    mod_base, list(self.str_to_int_mod_labels.keys()))
AssertionError: Modified base label (Z) not found in model alphabet (['m']).
```
The environment I use are: python==3.5, megalodon==2.1.0, guppy==3.6.1

Is there something wrong in my test?

Thank you in advance!

Best,
Peng

**Comment by marcus1487** [comment]
The `res_dna_r941_prom_modbases_5mC_CpG_v001.cfg` model uses the single letter code `m` for 5mC. This is in accordance with the proposed methylation storage format specification ([see here](https://github.com/samtools/hts-specs/pull/418)). Previous models used the code `Z` as there was no industry standard for modified base models. All modified base models released moving forward will attempt to adhere to the industry standard specifications.

In order to inspect the alphabet for any modified base model, see the `megalodon_extras modified_bases describe_alphabet` command ([docs here](https://nanoporetech.github.io/megalodon/extras_modified_bases.html#megalodon-extras-modified-bases-describe-alphabet)).

**Comment by PengNi** [comment]
Thank you.
