### ISSUE TITLE
Unsuccessful processing types 

### ISSUE THREAD

**Issue by replikation** [nanoporetech/megalodon#55]
Dear megalodon devs,

its currently unclear what `Unsuccessful processing types:` means in relation to the whole analysis. e.g. are unsuccessful processes retried (so just like a warning) or is this missing data in the end? 

for example, I got these as an output:

```bash
[15:49:56] Unsuccessful processing types:
    10.2% (   1971 reads) : Guppy server timeout (see --guppy-timeout argument)                             
     3.7% (    711 reads) : Pyguppy get completed reads invalid error "Something went wrong. return_code: result.failed"
     1.9% (    372 reads) : No alignment                                                                    
     0.0% (      1 reads) : Pyguppy pass read malformed error "Something went wrong, read dict might be malformed. return_code: result.failed"
```

does this mean 1971 reads are lost / not processed? 

thanks and best regards

**Comment by marcus1487** [comment]
Unsuccessful processing types short circuit a read from being included in one or more of the desired outputs. These unsuccessful processing types are somewhere between a warning and an error.

For these specific values, `Guppy server timeout (see --guppy-timeout argument)` and `Pyguppy get completed reads invalid error "Something went wrong. return_code: result.failed"` indicate that the Guppy server is overloaded and that basecalling has failed for these reads. See [this section in the README](https://github.com/nanoporetech/megalodon#guppy-models-and-parameters) for suggestions for rescuing reads from these failure modes. When a read fails basecalling it cannot be mapped to the reference and further cannot be processed for modified bases or variants. The `No alignment` value indicates that minimap did not produce a valid reference mapping for this read. Thus these 372 reads would be found into the basecall output, but not the mapping or further downstream outputs (mods and variants). I have not actually seen the `Pyguppy pass read malformed error "Something went wrong, read dict might be malformed. return_code: result.failed"` error mode myself, but this likely has to do with the overloaded basecalling server as well.

For a little bit more detail, a read can also be included in more than one unsuccessful processing type if both outputs are independent and caused separate errors. For example a read might basecall and map successfully, but fail to produce valid modified base and variant outputs due to some error in these processing steps.

There are many possible reasons that each output can fail, so all possible values in this list will not be documented, but the most common values should be documented in either the README or documentation.

**Comment by replikation** [comment]
thanks for clarifying this.

**Comment by PanZiwei** [comment]
Hi,
For Guppy relevant issues, we can reduce these issues by optimizing the parameter following the README file?
For alignment issue, is there a way to reduce the error?
Also, do you have an approximate percentage for the Unsuccessful processing types part?

Thank you so much for your help!

**Comment by marcus1487** [comment]
Yes. For guppy issues the recommendations in the README are the best place to start.

For alignment issues, there are many reasons for these types of issues. A couple common issues are contamination/unexpected species/sequences, high modified base content and poor reference quality. There are many more possibilities, and more knowledge about your experimental design may shed light on what to look for in your particular sample.

For approximate percentage of unsuccessful processing types, a very good run should ideally have <0.5% of reads with "no alignment" and no other errors. Some runs may be expected to have very high error rates. For example run with very high modified base context may be expected to produce >50% of reads producing "no alignment". Runs with very long reads and default parameters may cause guppy to fail/process reads too slowly in >50% of reads.

I hope this helps, but please post if you have more specific questions.
