### ISSUE TITLE
Problem using mod_basecalls and mod_mappings with trained taiyaki model on modified alphabet

### ISSUE THREAD

**Issue by organic-chemistry** [nanoporetech/megalodon#61]
Hello,
I trained a taiyaki model on a modified alphabet and succeeded in using mod_basecalls to retrieve the probability in the sam file.
Here one  strange thing is that the fa and the sam files only contain ACG and my modified base (here B and not T), whatsoever the probability in the sam file (which can vary from 0 to 255).

Also I don't succeed in using mod_mapping.
I tried this command line
`megalodon fast5_dir/  --outputs mod_mappings --output-directory test_bc2 --do-not-use-guppy-server --taiyaki-model-filename ../taiyaki/alphabet_B/model_checkpoint_00259.checkpoint --process 2  --device 0 1 2 3 --reference reference_sequence.fa --mod-map-base-conv B T --mod-map-emulate-bisulfite --disable-mod-calibration`

But the allignment does not work.
(I checked that the sequence can be alligned correctly using the fasta outputed by mod_basecall , replacing B by T and alligning it with minimap)

**Comment by organic-chemistry** [comment]
It seems that megalodon inverted B and T.
I read in the log:

`Using canonical alphabet ACGB and modified bases T=Brdu (alt to B)`

**Comment by marcus1487** [comment]
I'm not sure I understand the question regarding the comment "But the allignment does not work." Could you elaborate exactly what you expect and are seeing?

It looks as though the alphabet was misspecified in Taiyaki. Models are not required to use the canonical alphabet `ACGT`. It looks as though the canonical alphabet is set to `ACGB` and `T` is set as the alternative base. This can be modified in the Taiyaki mapped signal file using the `misc/convert_alphabet_or_inspect_mapped_signal_file.py` script. There is no script currently available to change the alphabet in the model file, but a custom python script could fix this (or manually editing the json model text file).

Additionally, as long as there are no custom layers used in the model I would highly recommend using the Taiyaki `bin/dump_json.py` script to output a model file to use with Guppy. This will be much more performant (the current setup can only use 2 devices due to only using 2 processes and likely not very efficiently).

**Comment by organic-chemistry** [comment]
I expect mod_mappings to align the basecall read to a reference sequence and so to provide the position of the basecall reads as well as the position of modified nucleotide.
Here what I get is 85 % of  unalign reads at the end of mod_mapping.
I guess it is because the basecall ouput reads with B and so the alignment does not work.

I think there may be a problem of convention between taiyaki and megalodon, because when I trained the model (in taiyaki) in the log it shows the correct alphabet:

```
* Reads not filtered by id
* Using alphabet definition: canonical alphabet ACGT with modified base(s) B=Brdu (alt to T)
```
I dumped the model in the json and there is a lign with:

"output_alphabet": "ACGBT",
            "modified_base_long_names": [
                "Brdu"
            ],
I changed the alphabet to ACGTB but I don't know how to use the json file in the command line.
Could you provide an example?
Best

**Comment by marcus1487** [comment]
This is a bug in how Taiyaki stores the alphabet. So switching the labels in the json successfully work around the issue. We are working on a fix for this now.

In order to use your new JSON model, you can copy the closest config in Guppy (in terms of flowcell, etc), then edit this config to point to the new json model file (`model_file` field) and store that model and config in the Guppy data directory.

**Comment by organic-chemistry** [comment]
Ok thank you.
I am not yet very familliar with guppy, but what you explained should be enoug.
In the mean time I used the following code
```
#!/usr/bin/env python3
import argparse
import json
import os
from taiyaki.cmdargs import AutoBool, FileExists, FileAbsent
from taiyaki.common_cmdargs import add_common_command_args
from taiyaki.helpers import file_md5, load_model, open_file_or_stdout ,save_model
from taiyaki.json import JsonEncoder

parser = argparse.ArgumentParser(description='Dump JSON representation of model',
                                 formatter_class=argparse.ArgumentDefaultsHelpFormatter)
#add_common_command_args(parser, ["output"])

parser.add_argument('--params', default=True, action=AutoBool,
                    help='Output parameters as well as model structure')
parser.add_argument('--output',type=str,
                    help='Output directory')

parser.add_argument('model', action=FileExists, help='Model checkpoint')


def main():
    args = parser.parse_args()
    model_md5 = file_md5(args.model)
    model = load_model(args.model)
    model.sublayers[-1].output_alphabet = "ACGTB"
    save_model(model,args.output)


if __name__ == "__main__":
    main()

```

that create a file named model_final.checkpoint in the ouput directory with the corrected alphabet (in my case)
Thank you
