### ISSUE TITLE
Feature request: include unmapped reads and soft clips in mod_mappings.bam

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/megalodon#72]
This would be really helpful for downstream processing and QC, if the mod_mappings alignment file had the unmapped regions of the read as well as unmapped reads being included in the bam. Is there any way to include this in megalodon, or a hacky way to enable this feature?

**Comment by marcus1487** [comment]
This is unfortunately not a very easy thing to do in the Megalodon framework. The `mod_mappings` are a reference anchored output. The `basecalls` (and `mod_basecalls`) are ignored by the point of calling the modified bases anchored to the reference (which eventually results in the `mod_mappings` output). So producing exactly this output is probably not feasible. It would also be a bit confusing to have basecall anchored mod calls concatenated with reference anchored modified calls in my opinion. These are fundamentally different calls based on the algorithms used (this is the main reason the calls from Megalodon are much more accurate).

I can think of a workaround using a number of other outputs that might suffice for your downstream processing requirements though. The `mod_basecalls` output will contain the unmapped reads. So filtering this for only the reads not found in the `mappings` output would give you the unmapped mod basecalls output. It might be faster to use the `mapping.summary.txt` instead of the `mod_mappings.bam` for this purpose since it is much smaller (i use this output quite often). 

The soft-clipped portions of the reads that lead to the `mod_mappings` is a bit trickier. Taking a look at the `mappings.summary.txt` file, it does not appear that the query start and stop is stored here. This should be a relatively simple fix to add to the next release. This would allow you to extract the portion of the reads from the `mod_basecalls` output that did not contribute to the final `mod_mapping` for each read.

I think this should get you all the information required for the described downstream processing, but please let me know if I am missing something or if something could use a better explaination.

**Comment by billytcl** [comment]
Right now I have to write a separate script to index which reads are doing what from the mod_basecalls.bam, and then use that to act on the mod_mappings.bam file. Not the most elegant, but it's basically what you're suggesting. 

I think your suggestion with adding the query start/stop positions would really help, as right now it's kind of clunky. One of the biggest advantages of having this output would be to streamline things like barcode demultiplexing which is not supported with the standard megalodon workflow.

**Comment by marcus1487** [comment]
For barcoding support, I would suggest running barcoding analysis on the `basecalls.fastq` output. Is there a specific reason to use the `mod_basecalls.bam` for this purpose? 

In #43 I've discussed that a future release may add support for barcoding by adding a tag to the BAM outputs. If that is the goal here then I would mark this as a duplicate. Are the other specific workflows that would require the merging of the basecall and reference anchored modified base outputs?

**Comment by billytcl** [comment]
Currently, it is a 2-3 step workflow that requires not only demultiplexing,
but recording which reads are mapped versus unmapped because the fastq and
mod_mappings don’t share all reads. As I said, I could use an auxiliary
script to parse this out but it is kind of clunky. In other cases the soft
clips may not necessarily be a barcode but has other features for secondary
analysis. Either way you are right - everything is in the fastq file.

**Comment by marcus1487** [comment]
The reads in the `mod_mappings.bam` should be a subset of the `basecalls.fastq` (I think this is what you were saying; just verifying).

For the feature request, I don't foresee adding the (mapping) clipped portions of basecalls to the `mod_mappings` output. I think this would be more confusing than helpful for most users, as the `mod_basecalls` and `mod_mappings` use fundamentally different algorithms to arrive at the modified base scores. I'm afraid mixing these could lead to more problems.

I would like to address any specific issues though. The barcoding is noted as a separate issue (#43 ) and a workaround has been outlined here. You note "other features for secondary analysis". I think the best approach here would be to derive these features from the `basecalls` output and then merge this with the `mod_mapping` output in your analysis pipeline. I hope that this suffices for your purposes, but again please let me know if there are specific issues that a feature could help solve.

**Comment by marcus1487** [comment]
The query start and end coordinates have been added to the mapping summary file in the latest release 2.2.7. Please open this issue back up if there any further points of data that would be helpful in the megalodon outputs.
