### ISSUE TITLE
running megalodon on existing guppy run

### ISSUE THREAD

**Issue by michieitel** [nanoporetech/megalodon#74]
Can I run megalodon on an existing guppy basecall run without the need to run guppy all over again given the guppy run was set to "-c dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg" ?

If yes what is the command for this?

**Comment by marcus1487** [comment]
The short answer is no. Unfortunately Megalodon requires the intermediate basecalling data which is generally discarded in a standard Guppy run.

It is possible to use Guppy output if the `--fast5_out` and `--post_out` options are specified in Guppy, but be aware that this will require approximately 10 times the disk space of the raw FAST5 files. This is not the recommended pipeline for Megalodon processing and is simply a workaround for certain pipelines.

Ideally Megalodon is intended to be run as the initial basecalling from a set of raw FAST5 files as Megalodon can produce largely the same outputs as Guppy. This would avoid the need to basecall the reads twice, but unfortunately this does help in the scenario when Guppy has already been run.

P.S. I would recommend using the most recent applicable model in [Rerio](https://github.com/nanoporetech/rerio) instead of the `dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg` config.

**Comment by michieitel** [comment]
Thank you very much for the information and tip
