### ISSUE TITLE
Megalodon seem to crash with no error message

### ISSUE THREAD

**Issue by hasindu2008** [nanoporetech/megalodon#75]
I have been trying to get Megalodon working for a PromethION sample on an HPC cluster node. However, when I launch Megalodon, it seems to crash just after a few seconds, but without any meaningful error message (see below). 

```
[10:00:44] Running Megalodon version 2.2.9
[10:00:44] Loading guppy base-calling backend
[10:00:52] Loading reference

[10:02:32] Using canonical alphabet ACGT and modified bases Y=6mA (alt to A); Z=5mC (alt to C)
[10:02:32] Preparing workers to process reads
```

The output files are empty. The generated log file also contains  no error message (attached).

[log.txt](https://github.com/nanoporetech/megalodon/files/5655729/log.txt)
[guppy_basecall_server_log-2020-12-08_10-00-45.log](https://github.com/nanoporetech/megalodon/files/5655730/guppy_basecall_server_log-2020-12-08_10-00-45.log)

I am not sure how to proceed.

**Comment by marcus1487** [comment]
It looks as though Megalodon is stuck trying to retrieve raw signal from the FAST5 files. Did the Megalodon command complete? The log file looks as though the run should be continuing from this point. Could there be some issue with the disk access for these FAST5 files (slow NFS)?

P.S. I would recommend using the most recent applicable model in [Rerio](https://github.com/nanoporetech/rerio) instead of the `dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg` config.

**Comment by hasindu2008** [comment]
Megalodon completed exited. So yeh, the command completed/crashed.

**Comment by marcus1487** [comment]
Was this run via a job scheduler? Is it possible that the job was killed due to memory limits?

The log is quite odd since the signal extractor processes completed initialization successfully [here](https://github.com/nanoporetech/megalodon/blob/master/megalodon/fast5_io.py#L255), but logged no more messages which shouldn't be possible without a segfault or some type of job short circuit.

**Comment by hasindu2008** [comment]
Yes, this is run via SGE scheduler. Last time I launched with a total of 128 GB RAM and this time with 256 GB of RAM (that is close to the max available on GPU nodes), but still the behaviour is the same.

I am not familiar with python, but usually, in compiled C/C++ programs, a segmentation fault would be usually printed to the stderr unless a sig_handler that prints nothing is implemented. There is no OOM log message in the system log of the corresponding GPU node as well, so unlikely to be a memory out.

**Comment by marcus1487** [comment]
Given that the signal enumeration seems to be failing, I would first suggest to turn down the resources assigned to this task. Could you try to re-run with the options: `--num-read-enumeration-threads 1 --num-extract-signal-processes 1`.

**Comment by hasindu2008** [comment]
Justed tried
```megalodon fast5/ --outputs per_read_mods mod_mappings mods --reference /scratch_local/33228.1.short.q/ref.fa --mod-motif Z CG 0 --devices 0 --processes 32 --guppy-server-path /share/ClusterShare/software/contrib/jamfer/ont-guppy-4.0.11/bin/guppy_basecall_server --output-directory /scratch_local/33228.1.short.q/output --num-read-enumeration-threads 1 --num-extract-signal-processes 1```
Sadly, the same outcome.

**Comment by marcus1487** [comment]
Could you try a run specifying `—processes 1`?

**Comment by hasindu2008** [comment]
Yes! Seems to be running all right so far.
Read Processing: 7294reads [14:02,  8.66reads/s, samples/s=1.1e+6]

**Comment by marcus1487** [comment]
I would suggest trying to dial up the number of processes to maximize performance. This still seems like a job scheduler issue though.
