### ISSUE TITLE
Question: 5hmC positive reads failing QC: lower Q-score threshold? 

### ISSUE THREAD

**Issue by ChloeDG** [nanoporetech/megalodon#78]
Hi Marcus! 

I am trying to do some benchmarking of the 5mC 5hmC calling with megadolon and I'm running into some probs. 
I sequenced some standards that are either Fully unmethtlated, fully methylated or fully hydroxymethylated in CpG contexts. 

Megadolon is nicely able to identity the absence of 5mC and 5hmC in our unmethylated control (good start), also correctly identified 5mC in our 5mC control with very low background levels of 5hmC detected (even better!). But all of my reads for the positive control for 5hmC are failing QC, so we have no coverage to detect anything. Is there a way to lower the Q-score threshold so that we can capture them? 

Best, 
Chloe.

**Comment by marcus1487** [comment]
Glad to hear that you are getting reasonable results with the first several tests!

For the all 5hmC sample, what exactly do you mean that the reads are failing QC. Are they not mapping to the reference genome? Megalodon does not perform q-score filtering internally on the reads (there may be such a setting in Guppy though).

P.S. I would recommend adding the setting `--mod-binary-threshold 0` with the 5hmC model. This model has a tendency to call 5hmC will lower probability, so in the aggregated results too many correct calls are filtered out. This setting forces Megalodon to make a call between C/5mC/5hmC at each and every site in each read. This has the side effect of adding some false classifications, and thus is not recommended for higher quality models (e.g. 5mC models).

**Comment by ChloeDG** [comment]
Yes, the 5hmC reads are not mapping to the reference genome. 
I used `--mod-binary-threshold 0` in the following: 

```
megalodon ${FAST53} --guppy-params "-d /media/tgfb/DATA/software/rerio/basecall_models" --guppy-config res_dna_r941_min_modbases_5mC_5hmC_CpG_v001.cfg --guppy-server-path /media/tgfb/DATA/software/ont-guppy/bin/guppy_basecall_server --outputs basecalls mods per_read_mods mod_basecalls mappings mod_mappings --write-mods-text --mappings-format bam --reference ${REF} --mod-motif mh CG 0 --mod-binary-threshold 0 --output-directory ${OUTPATH3} --devices 0 
```
The resulting fastq is 30MB but then only 1.6KB worth of reads are mapping, none of which have any 5hmC. 
Do you think it is Guppy that is bumping my reads or something else? 

Ubuntu 20.04
Megalodon version 2.2.9
Guppy version Version 4.2.2

**Comment by marcus1487** [comment]
This does not appear to be a result of Guppy filtering the reads. If the reads end up in the basecalls output, then Guppy successfully basecalled the reads. The reads are not mapping to the reference using minimap2 (under the hood). There are a very large number of reasons that this could happen. I don't want to speculate on the sample preparation method for this sample, but this could potential lead to issues with basecalling the reads. The basecaller was not trained with a very high percentage of 5hmC bases, but converting all CpG contexts to contain 5hmC should not cause issues this extreme.

Since the reads are not mapping Megalodon can't really do too much. The `--mod-binary-threshold 0` parameter only takes effect after the reads have been mapped and processed on the per-read level. If the reads don't map this must be addressed first either with a new model or sample validation.

**Comment by PaulaRomeroLozano** [comment]
Morning,

We are also trying to run megalodon to identify 5mC and 5hmC.
Basically we have 2 projects, one to detect 5mC and another one to detect 5mC and 5hmC.
I think I haven't seen this question asked in the threads so just to clarify:
Would res_dna_r941_min_modbases_5mC_v001.cfg call **only** 5mC or it would include also 5hmC as 5mC?
or
Would res_dna_r941_min_modbases_5mC_5hmC_v001.cfg model give me the same 5mC information as if I run res_dna_r941_min_modbases_5mC_v001.cfg **plus** 5hmC bases?

Do you think i would kill 2 birds with one stone by running res_dna_r941_min_modbases_5mC_5hmC_v001.cfg model?

Thank you very much for your help,
Regards,
Paula

**Comment by marcus1487** [comment]
This is a very key question, but unfortunately I don't have a very straightforward answer. Mainly this is because we don't have a very solid 5hmC ground truth dataset internally in order to completely assess this (though we are working on it). 

Given this caveat, my best current estimates would be that
1. `res_dna_r941_min_modbases_5mC_v001` does collapse 5mC+5hmC calls into 5mC calls
2. The 5mC calls from the `res_dna_r941_min_modbases_5mC_5hmC_v001` model are likely not going to be as accurate as the calls from `res_dna_r941_min_modbases_5mC_v001`. 

The medium term road map is to improve the 5mC+5hmC model performance so that the 5mC-only model can be deprecated. Currently the 5hmC model is considered a bit more experimental. This is a major focus internally though so hopefully `res_dna_r941_min_modbases_5mC_5hmC_v002` (next version) will replace both of these models before too long.

**Comment by ChloeDG** [comment]
Hi Marcus, 
To clarify, our control samples are synthetic DNA, that have all cytosines Fully-unmethtlated, methylated or hydroxymethylated, not just in CpG contexts. We have had problems with them before with other methylation callers, the reads don't align at all for the all-5hmC control, but we always use minimap2 for alignment, so do you think that is a good place to start looking for a solution..?  

We are also trying to call all context 5mC in our all-5mC control, and we are having the same problem as we did for the all-5hmC control. Instead of calling 5mC in the non-CpG context, Megalodon seems to be calling it as a deletion. Do you think this is because the controls are to concentrated for the modified bases or are we doing something weird in here:  

`
megalodon ${FAST5} --guppy-params "-d /media/tgfb/DATA/software/rerio/basecall_models" --guppy-config res_dna_r941_min_modbases_5mC_v001.cfg --guppy-server-path /media/tgfb/DATA/software/ont-guppy/bin/guppy_basecall_server --outputs basecalls mods per_read_mods mod_basecalls mappings mod_mappings --write-mods-text --mappings-format bam --sort-mappings --mod-map-emulate-bisulfite --mod-map-base-conv C T --mod-map-base-conv m C --reference ${REF} --output-directory ${OUTPATH} --devices 0
`

Also, what DNA samples was Megalodon trained with for detecting 5mC (all context) and 5hmC? 
:-)

**Comment by marcus1487** [comment]
The completely modified (in all context) samples are almost certainly the issue here. A number of issues arise in highly modified samples. We do not use such samples for training modified base models. 

Generally we use native samples (usually with methylation percentages in the 5-15% level) and try to mark them up as well as possible. See the modified base model training docs page for a summary of these approaches ([link here](https://nanoporetech.github.io/megalodon/modbase_training.html)). The diversity of organisms used in methylation models is a bit lower than canonical models since any methylation included must be marked up as accurately as possible (requiring orthogonal data types). 

For a fully modified samples, I would suggest training a canonical basecalling model from a partially (but highly; maybe 50-75% modified) modified base sample. This model would have a much better chance at mapping the fully modified sample. 

I hope this helps and best of luck in your research!

**Comment by ChloeDG** [comment]
Definitely helps. 
Thank you Marcus!
