### ISSUE TITLE
Poor modified base results observed for PromethION data

### ISSUE THREAD

**Issue by DAVID2022** [nanoporetech/megalodon#8]
Can you find some benchmark testing result of the DNA methylation detection model in guppy and megalodon such as the correlation of methylation frequency between bisulfite sequencing and megalodon for me? I can not find such kind of material on nanopore community or github.
Thank you so much for your kind help!

**Comment by DAVID2022** [comment]
In fact, when I apply megalodon on my own data, which is a sequencing result of a creature with a genome about 3GB, I got a terrible correlation (r=0.55) on the DNA methylation detection result of megalodon and traditional bisulfite sequence (only considering all sites whith a coverage above 3 reads  on both methods). Can anyone tell me where is the problem? my data or the software? 
Thank you so much for your kind help!
![image](https://user-images.githubusercontent.com/45761661/65561708-0be1e780-df76-11e9-9af2-c0d87e579147.png)

**Comment by marcus1487** [comment]
I have moved the benchmark query to a new issue (#9) in order to avoid too many topics in this issue thread.

The most likely reason for the poor correlation results here is the promethion data. In the ["Model Compatibility" section of the megalodon README](https://github.com/nanoporetech/megalodon#model-compatibility) it is noted that the default model is applicable only to "MinION or GridION R9.4.1 flowcells". As the promethion chip is slightly different a different model and megalodon calibration files are required to achieve optimal results. We are working towards expanding the platforms with modified base models, but at the moment only have a released model trained on MinION/GridION flowcells.

Given promethion data there are some steps that can be taken in order to improve performance without a new model. Looking at your correlation plot, it appears that the main issue is that too many sites identified by bisulfite as methylated are being called as canonical. Hopefully by increasing the hard threshold we may see improved correlation. The `megalodon/scripts/run_aggregation.py` script can be used in order to perform the aggregation step without re-running the basecalling computation. The pertinent argument to modify would be the `--mod-binary-threshold` value. This argument defaults to `0.75`. I would suggest increasing this value. Without looking into the data further it is hard to tell what value would be best, but `0.9` would seem reasonable.

We are also working on additional methods to avoid issues related to these hard thresholds. I will post here when these methods are released.

In order to investigate the results/data further the `megalodon/scripts/validate_results.py` script might be of use here as well. The bisulfite data could be processed in order to create a ground truth modified and canonical sites file. This file can be passed to the `validate_results.py` script via the `--ground-truth-data` argument. This will produce summary statistics and plots that should help in choosing a better threshold for this data set.

One final note, is that a coverage threshold of 3 is likely too low. I would suggest a coverage threshold around 10 for optimal results.

**Comment by DAVID2022** [comment]
Thank you so much for your kind help!
I am re-basecalling my PromethION FLO-PRO002 flow cell sequencing result using the model file of FLO-MIN106 to evaluate the consequence of calling PRO002 data using MIN106 model file.
We are looking forward to your new version megalodon. We hope you can release it soon.

**Comment by marcus1487** [comment]
Thinking about this a bit further, since there is actually good separation between the modified and unmodified positions, you might be able to correct this result by re-calibrating the modified base scores. I have not written up the docs for estimating calibration information (on my TODO list), but I can briefly describe the steps here.

1) Run megalodon with the `--disable-mod-calibration` and `--write-mods-text` flags set (don't need too many reads; 5k should be plenty).
2) Run `megalodon/scripts/generate_ground_truth_mod_llr_scores.py` script. In this particular case the `--ground-truth-data` control option should be specified with ground truth determined from the bisulfite data (with some hard thresholds for canonical and modified positions; something along the lines of <5% for canonical positions and >95% for modified positions).
3) Run `megalodon/scripts/calibrate_mod_llr_scores.py` script.

This will produce a `megalodon_mod_calibration.npz` file by default (set new output filename with `--out-filename` option). This file can then be passed into the main `megalodon` command via the `--mod-calibration-filename` option. This should result in vastly improved results for this analysis.

I still think that training a basecalling model for promethion would produce the best results here (understanding that this is much more of a compute and time investment), but hopefully this calibration can produce sufficient results for your purposes.

**Comment by marcus1487** [comment]
Given that the poor performance shown here is likely due to the model incompatibility between minion/gridion and promethion (unsupported by currently released model) data types I am going to close this issue.

It might still be good for other users to know if the re-calibration using the previous post helps alleviate this issue, so please do post here if this method does or does not resolve the poor performance.

**Comment by sdemirci** [comment]
Hi Marcus,

I am also using megalodon with promethion data. The correlation between bisulfite and megalodon calls is not bad (r= 0.73) but I would like to try to calibrate to see if it gets better. For that I am following your description above. In the second step, what type of value do you require for `is_mod` column of `--ground-truth-data` input file?

**Comment by marcus1487** [comment]
Hi @sdemirci ,

I think `True` and `False` are the probably the safest, but anything that the [pandas.read_csv](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) would interpret as a boolean variable would be acceptable.

**Comment by sdemirci** [comment]
Hi, 

Indeed the True/ False assignment has worked. The new results are better. I've got improved correlation (r=0.92) between the calibrated megalodon and bisulfite data.  Do you think this calibration file is applicable to other samples for example different species than it is calibrated for?

**Comment by marcus1487** [comment]
That is great to hear that the re-calibration has rescued the results. The modified base models currently released are trained only in native human and E. coli (K12) contexts. So 5mC outside of **C**G or C**C**WGG and 6mA outside of G**A**TC contexts were not included in training. There may be some signal at other contexts (megalodon will output scores), but this use case is not necessarily recommended and has not been tested. So if you wish to detect methylation in these contexts in other organisms, this calibration file should work well, but if you wish to detect methylation in different sequence contexts a new model should likely be trained.

As discussed in Clive's presentation at NCM 2019, an all context modified base model including 5mC and 6mA is in development and should be released soon (though we don't have an exact date for this release at this time). This model will initially be trained and calibrated only for MinION/GridION, but hopefully this same re-calibration step might be a stop-gap for that model as well, until a full promethion all-context mod base model is released. With this model and re-calibration file, the results should be completely applicable to other samples/organisms.

Hopefully this helps for now and moving forward.
